name: "Checkout with Git LFS"

description: "Also build Git LFS environment at checkout"

inputs:
  token:
    required: true
    default: ${{ github.token }}
  sparse-checkout:
    description: >
      Do a sparse checkout on given patterns.
      Each pattern should be separated with new lines
    required: false
    default: null
  sparse-checkout-cone-mode:
    description: >
      Specifies whether to use cone-mode when doing a sparse checkout.
    required: false
    default: true
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that event.
      Otherwise, uses the default branch.
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: 🔄 Checkout to the branch
      uses: actions/checkout@v5
      with:
        token: ${{ inputs.token }}
        submodules: recursive
        lfs: true
        ref: ${{ inputs.ref }}
      if: ${{ inputs.sparse-checkout == null }}

    - name: 🔄 Checkout to the branch
      uses: actions/checkout@v5
      with:
        token: ${{ inputs.token }}
        submodules: recursive
        lfs: true
        ref: ${{ inputs.ref }}
        sparse-checkout: ${{ inputs.sparse-checkout }}
        sparse-checkout-cone-mode: ${{ inputs.sparse-checkout-cone-mode }}
      if: ${{ inputs.sparse-checkout != null }}

    # https://github.com/actions/checkout/issues/270
    - run: |
        git lfs install
        git lfs pull
        git submodule foreach git lfs install
        git submodule foreach --recursive git lfs pull
      if: ${{ runner.os != 'Windows' }}
      shell: bash

    - run: |
        git lfs install
        git lfs pull
        git submodule foreach git lfs install
        git submodule foreach --recursive git lfs pull
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh

branding:
  icon: 'box'
  color: 'orange'